import { LAYERS,STEPS,PATHS,REFERENCES } from './content.js';
import { escapeHTML as e,evaluate,preset,newNotebook,restoreNotebook,validateNotebook,notebookHTML,NOTE_FIELDS } from './core.js';
import { MAX_BYTES } from './json.js';
const ROUTES=['aula','osi','praticar','caderno'];
const labels={aprendi:'O que aprendi',experimentei:'O que testei e observei',pendencias:'O que ainda quero revisar'};
export function createApp(doc,dependencies={}) {
 const win=doc.defaultView,main=doc.getElementById('main');
 const schedule=dependencies.setInterval??win.setInterval.bind(win),cancel=dependencies.clearInterval??win.clearInterval.bind(win);
 const state={route:ROUTES.includes(win.location.hash.slice(1))?win.location.hash.slice(1):'aula',book:newNotebook(),playing:false,speed:1,reduced:!!win.matchMedia?.('(prefers-reduced-motion: reduce)').matches,result:null,busy:false};
 let timer=null,toastTimer=null;
 function toast(message,error=false){const target=doc.getElementById('toast');target.textContent=message;target.hidden=false;target.setAttribute('role',error?'alert':'status');win.clearTimeout(toastTimer);toastTimer=win.setTimeout(()=>target.hidden=true,6500);}
 function stop(){state.playing=false;if(timer!==null)cancel(timer);timer=null;}
 function syncTimer(){if(timer!==null)cancel(timer);timer=null;if(state.playing&&!state.reduced&&state.route==='aula')timer=schedule(()=>{if(state.book.step>=STEPS.length-1){stop();render();return;}state.book.step++;state.book.layer=STEPS[state.book.step].layer;if(state.book.step===STEPS.length-1)stop();render();},6000/state.speed);}
 function heading(eyebrow,title,body){return `<span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p class="lead">${body}</p>`;}
 const references=()=>`<section class="section"><span class="eyebrow">PARA APROFUNDAR</span><ul class="references">${REFERENCES.map(([name,url])=>`<li><a href="${url}" target="_blank" rel="noopener noreferrer">${name} ↗</a></li>`).join('')}</ul></section>`;
 function topology(){
  const step=STEPS[state.book.step],path=PATHS[step.path];
  const nodes=[['pc',100,230,'Computador','192.0.2.10'],['switch',300,230,'Switch','LAN Ethernet'],['router',500,230,'Roteador','192.0.2.1'],['dns',755,105,'DNS','198.51.100.53'],['web',755,355,'Servidor web','203.0.113.80']];
  const coords=path?.match(/\d+/g).map(Number);
  const packet=path?`<circle r="9" fill="#f2d46b" stroke="#fff8d9" stroke-width="3"${state.playing&&!state.reduced?'':` cx="${coords.at(-2)}" cy="${coords.at(-1)}"`}>${state.playing&&!state.reduced?`<animateMotion path="${path}" dur="${6/state.speed}s" repeatCount="1" fill="freeze"/>`:''}</circle>`:'';
  return `<div class="topology"><svg viewBox="0 0 900 455" role="img" aria-labelledby="map-title map-desc"><title id="map-title">Caminho da aula: computador, switch, roteador, DNS e servidor web</title><desc id="map-desc">${e(step.title)}. A linha amarela destaca o caminho ilustrado nesta etapa; a posição do marcador em pausa indica seu destino.</desc><path class="wire" d="M100 230H500L755 105M500 230L755 355"/>${path?`<path class="active-path" d="${path}"/>`:''}${nodes.map(([id,x,y,name,address])=>`<g class="node" transform="translate(${x} ${y})"><rect x="-56" y="-30" width="112" height="60" rx="12"/><text text-anchor="middle" y="5">${name==='Computador'?'PC':name==='Servidor web'?'WEB':name}</text><text text-anchor="middle" y="55">${name}</text><text class="address" text-anchor="middle" y="75">${address}</text></g>`).join('')}${packet}</svg><p class="figure-caption">DESENHO SIMULADO · O marcador representa uma mensagem; não é uma captura real. Em pausa, ele aparece no destino do caminho.</p></div>`;
 }
 function lesson(){const step=STEPS[state.book.step];return heading('MISSÃO 01 · DO NOME À PÁGINA','Abra um site.<br>Entenda o caminho.','Veja o desenho ganhar movimento. Pause, avance uma etapa e explique por que cada protocolo aparece.')+`<div class="story-grid section"><section>${topology()}<div class="controls"><button id="play" data-action="play" aria-pressed="${state.playing}"${state.reduced?' disabled':''}>${state.playing?'Pausar':'Reproduzir aula'}</button><button class="quiet" data-action="previous"${state.book.step===0?' disabled':''}>← Voltar</button><button class="quiet" data-action="next"${state.book.step===STEPS.length-1?' disabled':''}>Avançar →</button><label for="speed">Velocidade</label><select id="speed">${[.75,1,1.5,2].map(v=>`<option value="${v}"${v===state.speed?' selected':''}>${v}×</option>`).join('')}</select><span class="counter">${state.book.step+1} / ${STEPS.length}</span></div>${state.reduced?'<p class="notice">Movimento reduzido: use Voltar e Avançar para estudar as cenas estáticas.</p>':''}</section><article class="panel soft-in"><span class="eyebrow">ETAPA ${String(state.book.step+1).padStart(2,'0')} · FUNÇÃO ILUSTRADA: CAMADA ${step.layer}</span><h2>${step.title}</h2><p>${step.body}</p><div class="packet">${e(step.packet)}</div><p class="question"><strong>Pare e explique:</strong><br>${step.question}</p><div class="controls"><button class="quiet" data-action="inspect-layer">Entender esta camada →</button></div></article></div><div class="step-list section" aria-label="Escolher etapa da aula">${STEPS.map((s,i)=>`<button data-action="step" data-value="${i}"${i===state.book.step?' aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span>${s.title}</button>`).join('')}</div><details class="section"><summary>O que este desenho simplifica?</summary><p>Usamos endereços de documentação e um nome fictício. IPs e rotas já estão configurados; o MAC do gateway já foi resolvido. DNS começa sem a resposta em cache. Escolhemos HTTPS sobre TCP, sem NAT, perdas ou retransmissões. HTTP/3 usa QUIC: esta aula não descreve todos os tipos de HTTPS.</p><p>O marcador pode resumir vários pacotes, como na negociação TLS. OSI é um modelo de referência: funções de sessão e apresentação costumam estar integradas a aplicações e bibliotecas na pilha TCP/IP. TLS não é definido rigidamente como “camada 6”.</p></details>`+references();}
 function layerDiagram(id){
  if(id===2)return '<div class="frame"><span>MAC destino</span><span>MAC origem</span><span>Dados + verificação</span></div>';
  if(id===6)return '<div class="frame"><span>Texto: Olá</span><span>UTF-8: 4F 6C C3 A1</span></div>';
  const illustrations={
   1:'<path d="M20 70h35V30h35v80h35V30h35v80h35V70h40"/><text x="255" y="75">0 · 1 · 0 · 1</text>',
   3:'<rect x="10" y="40" width="110" height="55" rx="8"/><text x="25" y="73">Rede A</text><path d="M125 68h65m-10-8 10 8-10 8"/><rect x="195" y="40" width="125" height="55" rx="8"/><text x="207" y="73">Roteador</text><path d="M325 68h60m-10-8 10 8-10 8"/><text x="398" y="73">Rede B</text>',
   4:'<text x="5" y="22">Cliente</text><text x="395" y="22">Servidor</text><path d="M20 45H445m-10-8 10 8-10 8M445 80H20m10-8-10 8 10 8M20 115H445m-10-8 10 8-10 8"/><text x="190" y="38">SYN</text><text x="170" y="73">SYN+ACK</text><text x="190" y="108">ACK</text>',
   5:'<rect x="10" y="40" width="140" height="60" rx="8"/><text x="25" y="76">Diálogo</text><path d="M160 70h100m-10-8 10 8-10 8"/><rect x="275" y="40" width="205" height="60" rx="8"/><text x="290" y="65">Sincronização</text><text x="290" y="86">e retomada</text>',
   7:'<rect x="10" y="38" width="150" height="65" rx="8"/><text x="25" y="77">Aplicação</text><path d="M165 70h110m-10-8 10 8-10 8"/><text x="188" y="55">HTTP</text><rect x="285" y="38" width="190" height="65" rx="8"/><text x="300" y="77">Serviço web</text>'
  };
  return `<svg viewBox="0 0 500 135" role="img" aria-label="Desenho da função da camada ${id}">${illustrations[id]}</svg>`;
 }
 function osi(){const layer=LAYERS.find(l=>l.id===state.book.layer);return heading('O MAPA PARA ORGANIZAR O RACIOCÍNIO','Sete camadas.<br>Uma comunicação.','Toque em uma camada para ver sua função, um desenho e uma tarefa. Depois conecte a ideia ao exercício.')+`<div class="osi-grid section"><div class="layers" role="group" aria-label="Selecionar uma camada OSI">${LAYERS.map(l=>`<button class="layer" data-action="layer" data-value="${l.id}" aria-pressed="${l.id===layer.id}"><span>${l.id}</span><div>${l.name}<small>${l.unit}</small></div></button>`).join('')}</div><article class="panel soft-in"><span class="eyebrow">CAMADA ${layer.id}</span><h2>${layer.name}</h2><p>${layer.role}</p><div class="mini-diagram">${layerDiagram(layer.id)}</div><p>${layer.example}</p><h3 class="section">Uma tarefa para lembrar</h3><p class="question">${layer.practice}</p><div class="controls"><a href="#praticar">Ir ao laboratório →</a><a href="#caderno">Anotar o que entendi →</a></div></article></div><div class="notice section">Use OSI para pensar em funções e investigar falhas. A internet usa a pilha TCP/IP; sessão e apresentação não precisam aparecer como protocolos separados. Uma conexão TCP e uma sessão de login da aplicação são conceitos diferentes.</div>`+references();}
 function results(){if(!state.result)return '<p class="result">Faça uma mudança e clique em <strong>Testar no modelo</strong>. Os resultados explicam o que acontece neste cenário.</p>';const r=state.result;return `<div class="status-grid">${[['local','Entre os computadores'],['remote','Caminho para outra rede'],['site','Site pelo nome']].map(([key,title])=>`<div class="status ${r[key]?'ok':'fail'}"><small>${title}</small><strong>${r[key]?'Funciona no modelo':'Requer revisão'}</strong></div>`).join('')}</div><div class="result" role="status">${r.issues.map(i=>`<article class="issue"><h3>Camada ${i.layer} · ${i.title}</h3><p>${i.help}</p><button class="quiet section" data-action="layer" data-value="${i.layer}">Rever a camada ${i.layer} →</button></article>`).join('')||'<p>Os três caminhos funcionam nas condições deste exercício. Explique os endereços, o gateway e o papel do DNS antes de encerrar.</p>'}</div>`;}
 function practice(){const c=state.book.config;return heading('MISSÃO 02 · UMA REDE PEQUENA','Monte. Quebre.<br>Descubra. Corrija.','Mude uma configuração, veja o que ainda funciona e use as camadas para organizar o diagnóstico.')+`<div class="controls">${[['normal','Rede funcionando'],['cabo','Desconectar cabo'],['subrede','Mudar sub-rede'],['gateway','Trocar gateway'],['dns','Trocar DNS'],['servico','Parar serviço']].map(([id,title])=>`<button class="quiet" data-action="preset" data-value="${id}">${title}</button>`).join('')}</div><div class="grid"><section class="panel"><span class="eyebrow">CONFIGURAÇÃO DO SEU EXERCÍCIO</span><h2>Uma LAN com máscara /24.</h2><p>Switch simples; roteador com 192.0.2.1/24. Você ajusta os dois computadores e o caminho de saída.</p>${[['client','IPv4 do computador A'],['peer','IPv4 do computador B'],['gateway','Gateway do computador A'],['dns','Servidor DNS do computador A']].map(([key,title])=>`<div class="field"><label for="config-${key}">${title}</label><input id="config-${key}" data-config="${key}" maxlength="15" value="${e(c[key])}" inputmode="decimal" autocomplete="off"></div>`).join('')}<div class="field check"><label for="config-cable"><input id="config-cable" type="checkbox" data-config="cable"${c.cable?' checked':''}>Cabo do computador A conectado</label></div><div class="field check"><label for="config-service"><input id="config-service" type="checkbox" data-config="service"${c.service?' checked':''}>Serviço HTTPS disponível no servidor</label></div><button data-action="test">Testar no modelo →</button></section><section class="panel"><span class="eyebrow">OBSERVE ANTES DE CONCLUIR</span><h2>O que mudou no caminho?</h2><div id="results">${results()}</div><p class="section">Guarde no caderno a alteração, o resultado e a explicação. Depois repita a topologia no Packet Tracer para comparar com um simulador mais completo.</p><a href="#caderno">Registrar meu experimento →</a></section></div><details class="section"><summary>Limites deste exercício</summary><p>A máscara é sempre /24. O roteador e o servidor DNS têm endereços fixos. O teste local considera apenas a LAN sem uma rota adicional; o cenário não modela VLANs, firewall, ARP, DHCP, NAT, IPv6 ou o estado completo de TCP/TLS. Alterar o computador B não impede, sozinho, o computador A de abrir o site. O desenho e o resultado não verificam sua rede real.</p></details>`+references();}
 function notebook(){return heading('UM REGISTRO DO QUE VOCÊ FEZ','Seu estudo fica<br>mais fácil de retomar.','Anote com suas palavras. Salve o caderno para continuar depois e use o relatório como registro do seu aprendizado.')+`<div class="grid section"><section class="panel notes">${NOTE_FIELDS.map(key=>`<div class="field"><label for="note-${key}">${labels[key]}</label><textarea id="note-${key}" data-note="${key}" maxlength="2000" rows="5">${e(state.book.notes[key])}</textarea><small>Até 2.000 caracteres. Ex.: alterei o gateway e comparei o acesso local com o remoto.</small></div>`).join('')}</section><aside class="panel"><span class="eyebrow">CONTINUAR DEPOIS</span><h2>Exporte antes de sair.</h2><p>O JSON inclui suas notas, a etapa da aula, a camada selecionada e a configuração do exercício. O HTML organiza um relatório para leitura e impressão.</p><div class="controls"><button data-action="export">Caderno JSON ↓</button><button class="quiet" data-action="report">Relatório HTML ↓</button></div><div class="field section"><label for="restore">Restaurar caderno JSON · até 2 MB</label><input id="restore" type="file" accept=".json"><small>A importação valida a versão, as notas e os endereços antes de substituir seu caderno. Use IPv4s com sintaxe válida para exportar a configuração, mesmo quando ela está errada no cenário.</small></div><p class="notice">As notas ficam na memória desta página, sem envio para o servidor ou armazenamento permanente no navegador. Fechar ou recarregar pode encerrar o trabalho.</p></aside></div>`;}
 const views={aula:lesson,osi,praticar:practice,caderno:notebook};
 function render(preserve=true){const active=doc.activeElement,id=active?.id,action=active?.dataset?.action,value=active?.dataset?.value;let selection;try{selection=[active.selectionStart,active.selectionEnd];}catch{}main.innerHTML=views[state.route]();doc.documentElement.dataset.reduced=String(state.reduced);doc.getElementById('motion').setAttribute('aria-pressed',String(state.reduced));doc.getElementById('motion').textContent=state.reduced?'Ativar movimento':'Reduzir movimento';for(const link of doc.querySelectorAll('nav a')){if(link.hash==='#'+state.route)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');}if(preserve){const target=id?doc.getElementById(id):[...main.querySelectorAll('[data-action]')].find(b=>b.dataset.action===action&&b.dataset.value===value);target?.focus({preventScroll:true});if(selection&&target?.setSelectionRange)try{target.setSelectionRange(...selection);}catch{}}}
 function navigate(){stop();state.route=ROUTES.includes(win.location.hash.slice(1))?win.location.hash.slice(1):'aula';render(false);main.focus({preventScroll:true});win.scrollTo?.({top:0,behavior:state.reduced?'instant':'smooth'});}
 function download(content,name,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const anchor=doc.createElement('a');anchor.href=url;anchor.download=name;doc.body.append(anchor);anchor.click();anchor.remove();win.setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Arquivo exportado. Revise suas notas antes de compartilhar.');}
 doc.getElementById('motion').addEventListener('click',()=>{state.reduced=!state.reduced;stop();render();});
 win.addEventListener('hashchange',navigate);
 main.addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(!button||button.disabled)return;const action=button.dataset.action,value=button.dataset.value;try{if(action==='play'){if(state.playing)stop();else if(!state.reduced){if(state.book.step===STEPS.length-1)state.book.step=0;state.playing=true;syncTimer();}}else if(['next','previous','step'].includes(action)){stop();const n=action==='next'?state.book.step+1:action==='previous'?state.book.step-1:Number(value);if(!Number.isInteger(n)||n<0||n>=STEPS.length)throw new Error('Etapa inválida.');state.book.step=n;state.book.layer=STEPS[n].layer;}else if(action==='inspect-layer'){stop();state.book.layer=STEPS[state.book.step].layer;win.location.hash='osi';return;}else if(action==='layer'){const n=Number(value);if(!Number.isInteger(n)||n<1||n>7)throw new Error('Camada inválida.');stop();state.book.layer=n;if(state.route!=='osi'){win.location.hash='osi';return;}}else if(action==='preset'){state.book.config=preset(value);state.result=null;}else if(action==='test')state.result=evaluate(state.book.config);else if(action==='export'){validateNotebook(state.book);download(JSON.stringify(state.book,null,2),'rede-em-movimento-caderno.json');return;}else if(action==='report'){download(notebookHTML(state.book),'rede-em-movimento-estudo.html','text/html;charset=utf-8');return;}render();}catch(error){toast(error.message,true);}});
 main.addEventListener('input',event=>{const target=event.target;if(target.dataset.note&&NOTE_FIELDS.includes(target.dataset.note)){if(target.value.length>2000){toast('Use até 2.000 caracteres por nota.',true);return;}state.book.notes[target.dataset.note]=target.value;}if(target.dataset.config&&['client','peer','gateway','dns'].includes(target.dataset.config)){state.book.config[target.dataset.config]=target.value.trim().slice(0,15);state.result=null;const result=doc.getElementById('results');if(result)result.innerHTML=results();}});
 main.addEventListener('change',async event=>{const target=event.target;try{if(target.id==='speed'){const speed=Number(target.value);if(![.75,1,1.5,2].includes(speed))throw new Error('Velocidade inválida.');state.speed=speed;syncTimer();render();}else if(target.dataset.config&&['cable','service'].includes(target.dataset.config)){state.book.config[target.dataset.config]=target.checked;state.result=null;render();}else if(target.id==='restore'){const file=target.files?.[0];if(!file)return;if(!file.size||file.size>MAX_BYTES)throw new Error('Use um JSON UTF-8 de até 2 MB.');state.busy=true;const text=new TextDecoder('utf-8',{fatal:true}).decode(new Uint8Array(await file.arrayBuffer()));const restored=restoreNotebook(text);stop();state.book=restored;state.result=null;state.busy=false;render();toast('Caderno validado e restaurado.');}}catch(error){state.busy=false;toast(error.message,true);}});
 render(false);return {state,render,destroy(){stop();win.clearTimeout(toastTimer);win.removeEventListener('hashchange',navigate);}};
}
if(typeof document!=='undefined'&&document.getElementById('main'))createApp(document);
