import test from 'node:test';
import assert from 'node:assert/strict';
import { STEPS,LAYERS } from '../content.js';
import { DEFAULT_CONFIG,evaluate,preset,newNotebook,restoreNotebook,notebookHTML,ipv4 } from '../core.js';
test('normal network reaches local, remote and the named site',()=>{assert.deepEqual({...evaluate(DEFAULT_CONFIG()),issues:[]},{local:true,remote:true,site:true,issues:[]});assert.deepEqual(evaluate(DEFAULT_CONFIG()).issues,[]);});
for(const [name,expected] of [['cabo',[false,false,false]],['subrede',[false,true,true]],['gateway',[true,false,false]],['dns',[true,true,false]],['servico',[true,true,false]]])
 test('fault '+name+' has independent path outcomes',()=>{const r=evaluate(preset(name));assert.deepEqual([r.local,r.remote,r.site],expected);assert.ok(r.issues.length>0);});
test('malformed DNS and gateway do not prevent local communication',()=>{const c=DEFAULT_CONFIG();c.dns='999.1.1.1';const r=evaluate(c);assert.equal(r.local,true);assert.equal(r.remote,true);assert.equal(r.site,false);c.gateway='';assert.equal(evaluate(c).local,true);assert.equal(evaluate(c).remote,false);});
test('invalid peer does not block the client remote route',()=>{const c=DEFAULT_CONFIG();c.peer='192.0.2.255';const r=evaluate(c);assert.equal(r.local,false);assert.equal(r.remote,true);});
test('reserved hosts and duplicate addresses cannot satisfy local communication',()=>{for(const value of ['192.0.2.0','192.0.2.255','192.0.2.10']){const c=DEFAULT_CONFIG();c.peer=value;assert.equal(evaluate(c).local,false);}});
test('IPv4 parsing rejects impossible octets and extra zeros',()=>{for(const value of ['999.1.1.1','192.0.02.1','192.0.2','x','1.2.3.4/24'])assert.throws(()=>ipv4(value));assert.deepEqual(ipv4('192.0.2.10'),[192,0,2,10]);});
test('notebook restores step, layer, intentionally wrong configuration and notes',()=>{const b=newNotebook();b.step=STEPS.length-1;b.layer=2;b.config=preset('gateway');b.notes.aprendi='O acesso local funciona mesmo com gateway errado.';assert.deepEqual(JSON.parse(JSON.stringify(restoreNotebook(JSON.stringify(b)))),b);});
test('notebook rejects ambiguous and incompatible input before state changes',()=>{for(const mutate of [b=>b.schema_version=true,b=>b.kind='netguard-wifi-review',b=>b.step=STEPS.length,b=>b.layer=8,b=>b.config.cable='true',b=>b.config.extra='x',b=>b.notes.aprendi='x'.repeat(2001)]){const b=newNotebook();mutate(b);assert.throws(()=>restoreNotebook(JSON.stringify(b)));}const s=JSON.stringify(newNotebook()).replace('"schema_version":1','"schema_version":1,"schema_version":1');assert.throws(()=>restoreNotebook(s),/repetida/);});
test('study report escapes notes and blocks scripts',()=>{const b=newNotebook();b.notes.aprendi='<img src=x onerror="alert(1)"><script>x</script>';const out=notebookHTML(b);assert.ok(!out.includes('<script>'));assert.ok(!out.includes('<img'));assert.ok(out.includes('&lt;script&gt;'));assert.ok(out.includes("default-src 'none'"));});
test('the story keeps DNS before TCP and displays all seven distinct OSI layers',()=>{assert.deepEqual(LAYERS.map(l=>l.id),[7,6,5,4,3,2,1]);assert.equal(STEPS[6].packet.includes('SYN'),true);assert.equal(STEPS[7].packet.includes('SYN + ACK'),true);assert.equal(STEPS[8].packet.includes('ACK'),true);assert.equal(STEPS[9].title.includes('TLS'),true);});
